FROM openjdk:11
MAINTAINER keaton naidoo <keanaido021@student.wethinkcode.co.za>

WORKDIR /app

COPY target/SocketServer*.jar RobotWorldsServer.jar

EXPOSE 5050
CMD ["java", "-jar", "RobotWorldsServer.jar","-p","5050"]